CREATE TABLE listOfOrders
(listOfOrdersId INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
numberOfOrder INT NOT NULL,
price INT NOT NULL,
passengerId INT NOT NULL,
orderTypeId INT NOT NULL,
driverId INT NOT  NULL,
cityId INT NOT NULL,
streetId INT NOT NULL,
carId INT NOT NULL,
FOREIGN KEY(orderTypeId) REFERENCES orderType(orderTypeId),
FOREIGN KEY(passengerId) REFERENCES passenger(passengerId),
FOREIGN KEY(driverId) REFERENCES driver(driverId)
FOREIGN KEY(cityId) REFERENCES city(cityId),
FOREIGN KEY(streetId) REFERENCES street(streetId),
FOREIGN KEY(carId) REFERENCES car(carId));
SELECT * FROM listOfOrders;

CREATE TABLE orderType
(orderTypeId INT PRIMARY KEY NOT NULL,
orderTypeName VARCHAR(20) NOT NULL);
SELECT * FROM orderType;


CREATE TABLE car
(carId INT PRIMARY KEY NOT NULL,
carName VARCHAR(30) NOT NULL,
numberOfTheCar VARCHAR(8) NOT NULL,
carTypeId INT NOT NULL,
FOREIGN KEY (carTypeId) REFERENCES carType(carTypeId));
SELECT * FROM car;

CREATE TABLE carType
(carTypeId INT PRIMARY KEY NOT NULL,
carTypeName VARCHAR(35) NOT NULL);

CREATE TABLE driver
(driverId INT PRIMARY  KEY NOT  NULL,
name VARCHAR(30) NOT NULL,
phoneNumber VARCHAR(10) NOT NULL);

CREATE TABLE passenger
(passengerId INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
name VARCHAR(30) NOT NULL,
phoneNumber VARCHAR(10) NOT NULL);

CREATE TABLE payment
(paymentId INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
listOfOrdersId INT NOT NULL,
bankId INT NOT NULL,
FOREIGN KEY (listOfOrdersId) REFERENCES listOfOrders(listOfOrdersId),
FOREIGN KEY(bankId) REFERENCES bank(bankId));

CREATE TABLE bank
(bankId INT PRIMARY KEY NOT NULL,
bankName VARCHAR(30) NOT NULL);

CREATE TABLE city
(cityId INT PRIMARY KEY INT NOT NULL,
cityName VARCHAR(30) NOT NULL,
cityCode INT NOT NULL);

CREATE TABLE street
(streetId INT PRIMARY KEY NOT NULL,
streetName VARCHAR(30) NOT NULL,
streetNumber INT NOT NULL);

SELECT * FROM street;
SELECT * FROM city;
SELECT * FROM bank;
SELECT * FROM payment;
SELECT * FROM passenger;
SELECT * FROM driver;
SELECT * FROM carType;